spring.datasource.url=jdbc:postgresql://db.uydksrlbnddxkicbfbim.supabase.co:5432/postgres?sslmode=require

spring.datasource.username=postgres
spring.datasource.password=p5K/h!K4ch423bh

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
